import json
import os

syllabus = {
    "01_Engineering_Mathematics": [
        "Discrete_Mathematics - Propositional_Logic",
        "Discrete_Mathematics - First_Order_Logic",
        "Discrete_Mathematics - Sets",
        "Discrete_Mathematics - Relations",
        "Discrete_Mathematics - Functions",
        "Discrete_Mathematics - Partial_Orders",
        "Discrete_Mathematics - Lattices",
        "Discrete_Mathematics - Monoids",
        "Discrete_Mathematics - Groups",
        "Discrete_Mathematics - Graph_Theory - Connectivity",
        "Discrete_Mathematics - Graph_Theory - Matching",
        "Discrete_Mathematics - Graph_Theory - Coloring",
        "Discrete_Mathematics - Combinatorics - Counting",
        "Discrete_Mathematics - Combinatorics - Recurrence_Relations",
        "Discrete_Mathematics - Combinatorics - Generating_Functions",
        "Linear_Algebra - Matrices",
        "Linear_Algebra - Determinants",
        "Linear_Algebra - System_of_Linear_Equations",
        "Linear_Algebra - Eigenvalues",
        "Linear_Algebra - Eigenvectors",
        "Linear_Algebra - LU_Decomposition",
        "Calculus - Limits",
        "Calculus - Continuity",
        "Calculus - Differentiability",
        "Calculus - Maxima_and_Minima",
        "Calculus - Mean_Value_Theorem",
        "Calculus - Integration",
        "Probability_and_Statistics - Random_Variables",
        "Probability_and_Statistics - Uniform_Distribution",
        "Probability_and_Statistics - Normal_Distribution",
        "Probability_and_Statistics - Exponential_Distribution",
        "Probability_and_Statistics - Poisson_Distribution",
        "Probability_and_Statistics - Binomial_Distribution",
        "Probability_and_Statistics - Mean",
        "Probability_and_Statistics - Median",
        "Probability_and_Statistics - Mode",
        "Probability_and_Statistics - Standard_Deviation",
        "Probability_and_Statistics - Conditional_Probability",
        "Probability_and_Statistics - Bayes_Theorem"
    ],
    "02_Digital_Logic": [
        "Boolean_Algebra",
        "Combinational_Circuits",
        "Sequential_Circuits",
        "Logic_Minimization",
        "Number_Representation",
        "Fixed_Point_Arithmetic",
        "Floating_Point_Arithmetic"
    ],
    "03_Computer_Organization_and_Architecture": [
        "Machine_Instructions",
        "Addressing_Modes",
        "ALU",
        "Datapath",
        "Control_Unit",
        "Instruction_Pipelining",
        "Pipeline_Hazards",
        "Memory_Hierarchy - Cache_Memory",
        "Memory_Hierarchy - Main_Memory",
        "Memory_Hierarchy - Secondary_Memory",
        "I_O_Interface - Interrupts",
        "I_O_Interface - DMA"
    ],
    "04_Programming_and_Data_Structures": [
        "Programming_in_C",
        "Recursion",
        "Arrays",
        "Stacks",
        "Queues",
        "Linked_Lists",
        "Trees",
        "Binary_Search_Trees",
        "Binary_Heaps",
        "Graphs"
    ],
    "05_Algorithms": [
        "Searching",
        "Sorting",
        "Asymptotic_Analysis - Time_Complexity",
        "Asymptotic_Analysis - Space_Complexity",
        "Greedy_Algorithms",
        "Dynamic_Programming",
        "Divide_and_Conquer",
        "Graph_Traversal",
        "Minimum_Spanning_Tree",
        "Shortest_Path"
    ],
    "06_Theory_of_Computation": [
        "Regular_Expressions",
        "Finite_Automata",
        "Context_Free_Grammar",
        "Pushdown_Automata",
        "Regular_Languages",
        "Context_Free_Languages",
        "Pumping_Lemma",
        "Turing_Machines",
        "Undecidability"
    ],
    "07_Compiler_Design": [
        "Lexical_Analysis",
        "Parsing",
        "Syntax_Directed_Translation",
        "Runtime_Environments",
        "Intermediate_Code_Generation",
        "Local_Optimization",
        "Data_Flow_Analysis - Constant_Propagation",
        "Data_Flow_Analysis - Liveness_Analysis",
        "Data_Flow_Analysis - Common_Subexpression_Elimination"
    ],
    "08_Operating_System": [
        "System_Calls",
        "Processes",
        "Threads",
        "Inter_Process_Communication",
        "Concurrency",
        "Synchronization",
        "Deadlock",
        "CPU_Scheduling",
        "Memory_Management",
        "Virtual_Memory",
        "File_Systems"
    ],
    "09_Database_Management_System": [
        "ER_Model",
        "Relational_Model",
        "Relational_Algebra",
        "Tuple_Calculus",
        "SQL",
        "Integrity_Constraints",
        "Normalization",
        "File_Organization",
        "Indexing - B_Trees",
        "Indexing - B_Plus_Trees",
        "Transactions",
        "Concurrency_Control"
    ],
    "10_Computer_Networks": [
        "OSI_Model",
        "TCP_IP_Model",
        "Data_Link_Layer - Framing",
        "Data_Link_Layer - Error_Detection",
        "Data_Link_Layer - MAC",
        "Data_Link_Layer - Ethernet",
        "Routing_Protocols - Shortest_Path",
        "Routing_Protocols - Flooding",
        "Routing_Protocols - Distance_Vector",
        "Routing_Protocols - Link_State",
        "Network_Layer - Fragmentation",
        "Network_Layer - IP_Addressing",
        "Network_Layer - IPv4",
        "Network_Layer - CIDR",
        "Network_Layer - ARP",
        "Network_Layer - DHCP",
        "Network_Layer - ICMP",
        "Network_Layer - NAT",
        "Transport_Layer - UDP",
        "Transport_Layer - TCP",
        "Transport_Layer - Flow_Control",
        "Transport_Layer - Congestion_Control",
        "Transport_Layer - Sockets",
        "Application_Layer - DNS",
        "Application_Layer - SMTP",
        "Application_Layer - HTTP",
        "Application_Layer - FTP",
        "Application_Layer - Email"
    ]
}

target_path = os.path.join(os.path.dirname(__file__), "data", "gate_cse_syllabus.json")
with open(target_path, "w") as f:
    json.dump(syllabus, f, indent=4)
print("Syllabus updated!")
