steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/ai-study-buddy-498914/cloud-run-source-deploy/ai-study-buddy', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/ai-study-buddy-498914/cloud-run-source-deploy/ai-study-buddy']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-study-buddy'
      - '--image'
      - 'us-central1-docker.pkg.dev/ai-study-buddy-498914/cloud-run-source-deploy/ai-study-buddy'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/ai-study-buddy-498914/cloud-run-source-deploy/ai-study-buddy'
